dns_nodes: "{{ openshift_install_nodes | mandatory }}"
dns_base_domain: "{{ openshift_install_base_domain | mandatory }}"
dns_cluster_name: "{{ openshift_install_cluster_name | mandatory }}"
dns_zone: "{{ dns_cluster_name }}.{{ dns_base_domain }}"
dns_primary_grid: "{{ openshift_install_dns_primary_grid | mandatory }}"
dns_provider: "{{ openshift_install_dns | mandatory }}"
dns_dhcp_enabled: "{{ openshift_install_dhcp | d(false) }}"
dns_network_view: "{{ openshift_install_dns_network_view | d('default') }}"
dns_network: "{{ openshift_install_network | d('') }}"
dns_state: "{{ openshift_install_dns_state | d('present') }}"