- name: master | Add monitor for master node
  f5networks.f5_modules.bigip_monitor_https:
    name: "backend-openshift-api-monitor"
    state: present
    send: "GET /readyz HTTP/1.1\r\nhost:localhost\r\nconnection:close\r\n\r\n"
    receive: "ok"
    provider: "{{ load_balancer_provider }}"

- name: master | Create backend-openshift-router
  f5networks.f5_modules.bigip_pool:
    state: present
    name: "{{ openshift_install_cluster_name }}-backend-openshift-api-server"
    monitors:
      - "backend-openshift-api-monitor"
    provider: "{{ load_balancer_provider }}"

- name: master | Add pool member to backend-openshift-api-server
  f5networks.f5_modules.bigip_pool_member:
    pool: "{{ openshift_install_cluster_name }}-backend-openshift-api-server"
    name: "{{ item.name | mandatory }}-{{ openshift_install_cluster_name }}"
    host: "{{ item.ipaddr }}"
    port: 6443
    provider: "{{ load_balancer_provider }}"
  loop: "{{ openshift_install_nodes | selectattr('role', 'equalto', 'master') }}"

- name: master | Add virtual server for master
  f5networks.f5_modules.bigip_virtual_server:
    state: present
    name: "{{ openshift_install_cluster_name }}-frontend-openshift-api-server"
    destination: "{{ load_balancer_api_vip }}"
    port: 6443
    pool: "{{ openshift_install_cluster_name }}-backend-openshift-api-server"
    snat: Automap
    provider: "{{ load_balancer_provider }}"
