- name: master | Add monitor for master node
  f5networks.f5_modules.bigip_monitor_https:
    name: "backend-openshift-api-monitor"
    state: present
    send: "GET /readyz HTTP/1.1\r\nhost:localhost\r\nconnection:close\r\n\r\n"
    receive: "ok"
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no

- name: master | Create backend-openshift-router
  f5networks.f5_modules.bigip_pool:
    state: present
    name: "{{ vsphere_upi_cluster_name }}-backend-openshift-api-server"
    monitors:
      - "backend-openshift-api-monitor"
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no

- name: master | Add pool member to backend-openshift-api-server
  f5networks.f5_modules.bigip_pool_member:
    pool: "{{ vsphere_upi_cluster_name }}-backend-openshift-api-server"
    name: "{{ item.name }}"
    host: "{{ item.ipaddr }}"
    port: 6443
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no
  loop: "{{ vsphere_upi_nodes }}"

- name: master | Add virtual server for master
  f5networks.f5_modules.bigip_virtual_server:
    state: present
    name: "{{ vsphere_upi_cluster_name }}-frontend-openshift-api-server"
    destination: "{{ vsphere_upi_api_vip }}"
    port: 6443
    pool: "{{ vsphere_upi_cluster_name }}-backend-openshift-api-server"
    snat: Automap
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no
