- name: mc | Create backend-machine-config-server
  f5networks.f5_modules.bigip_pool:
    state: present
    name: "{{ vsphere_upi_cluster_name }}-backend-machine-config-server"
    monitors:
      - tcp
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no

- name: mc | Add pool member to backend-machine-config-server
  f5networks.f5_modules.bigip_pool_member:
    pool: "{{ vsphere_upi_cluster_name }}-backend-machine-config-server"
    name: "{{ item.name }}"
    host: "{{ item.ipaddr }}"
    port: 22623
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no
  loop: "{{ vsphere_upi_nodes }}"

- name: mc | Add virtual server for machine config
  f5networks.f5_modules.bigip_virtual_server:
    state: present
    name: "{{ vsphere_upi_cluster_name }}-frontend-machine-config-server"
    destination: "{{ vsphere_upi_api_vip }}"
    port: 22623
    pool: "{{ vsphere_upi_cluster_name }}-backend-machine-config-server"
    snat: Automap
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no
