- name: worker | Create backend-openshift-router
  f5networks.f5_modules.bigip_pool:
    state: present
    name: "{{ openshift_install_cluster_name }}-backend-openshift-router"
    monitors:
      - tcp
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no

- name: worker | Add pool member to backend-openshift-router
  f5networks.f5_modules.bigip_pool_member:
    pool: "{{ openshift_install_cluster_name }}-backend-openshift-router"
    name: "{{ item.name }}-{{ openshift_install_cluster_name }}"
    host: "{{ item.ipaddr }}"
    port: 443
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no
  loop: "{{ openshift_install_nodes }}"

- name: worker | Add virtual server for worker
  f5networks.f5_modules.bigip_virtual_server:
    state: present
    name: "{{ openshift_install_cluster_name }}-frontend-openshift-router"
    destination: "{{ load_balancer_ingress_vip }}"
    port: 443
    pool: "{{ openshift_install_cluster_name }}-backend-openshift-router"
    snat: Automap
    provider:
      server: "{{ load_balancer_provider_host }}"
      user: "{{ load_balancer_provider_username }}"
      password: "{{ load_balancer_provider_password }}"
      validate_certs: no
