load_balancer_provider_host: "{{ openshift_install_lb_host | mandatory }}"
load_balancer_provider_username: "{{ openshift_install_lb_username | mandatory }}"
load_balancer_provider_password: "{{ openshift_install_lb_password | mandatory }}"

load_balancer_api_vip: "{{ openshift_install_api_vip | mandatory }}"
load_balancer_ingress_vip: "{{ openshift_install_ingress_vip | mandatory }}"