# VMWare spec
configure_hardware_version: "{{ vpshere_upi_hardware_version | default('VMX_17') }}"
configure_datacenter: "{{ openshift_install_datacenter | mandatory }}"
configure_cluster: "{{ openshift_install_cluster | mandatory }}"
configure_datastore: "{{ openshift_install_datastore | mandatory }}"
configure_network_name: "{{ openshift_install_network_name | mandatory }}"
configure_folder: "{{ openshift_install_folder | mandatory }}"
configure_host: "{{ openshift_install_vsphere_host | mandatory }}"
configure_username: "{{ openshift_install_vsphere_username | mandatory }}"
configure_password: "{{ openshift_install_vsphere_password | mandatory }}"

# Resources spec
configure_master_mib: "{{ vpshere_upi_master_mib | default(16384) }}"
configure_master_cpu_count: "{{ openshift_install_master_cpu_count | default(4) }}"
configure_master_cpu_cps: "{{ openshift_install_master_cpu_cps | default(2) }}"

# Networking
configure_interface_name: "{{ openshift_install_interface_name | default('ens160') }}"
configure_default_route: "{{ openshift_install_default_route | mandatory }}"
configure_dns_servers: "{{ openshift_install_dns_servers | mandatory }}"

# Openshift spec
configure_network_type: "{{ openshift_install_network_type | default('OpenShiftSDN') }}"
configure_network: "{{ openshift_install_network | mandatory }}"
configure_base_domain: "{{ openshift_install_base_domain | mandatory }}"
configure_cluster_name: "{{ openshift_install_cluster_name | mandatory }}"
configure_ssh_key: "{{ openshift_install_ssh_key | mandatory }}"
configure_pull_secret: "{{ openshift_install_pull_secret | mandatory }}"

# DHCP
configure_dhcp: "{{ openshift_install_dhcp | default('false') | bool }}"
configure_dhcp_reservation: "{{ openshift_install_dhcp_reservation | default('true') | bool }}"
configure_dns_provider_host: "{{ openshift_install_dns_host | mandatory }}"
configure_dns_provider_username: "{{ openshift_install_dns_username | mandatory }}"
configure_dns_provider_password: "{{ openshift_install_dns_password | mandatory }}"