# VMWare spec
configure_hardware_version: "{{ vpshere_upi_hardware_version | default('VMX_17') }}"
configure_datacenter: "{{ openshift_install_datacenter | mandatory }}"
configure_cluster: "{{ openshift_install_cluster | mandatory }}"
configure_datastore: "{{ openshift_install_datastore | mandatory }}"
configure_network_name: "{{ openshift_install_network_name | mandatory }}"
configure_folder: "{{ openshift_install_folder | mandatory }}"
configure_vsphere: "{{ openshift_install_vsphere | d(lookup('community.hashi_vault.hashi_vault', 'secret={{ openshift_install_vault_secret_vsphere }} token={{ openshift_install_vault_token }} validate_certs=false url={{ openshift_install_vault_url }}')) }}"

# Resources spec
configure_master_mib: "{{ vpshere_upi_master_mib | default(32768) }}"
configure_master_cpu_count: "{{ openshift_install_master_cpu_count | default(6) }}"
configure_master_cpu_cps: "{{ openshift_install_master_cpu_cps | default(2) }}"

# Networking
configure_interface_name: "{{ openshift_install_interface_name | default('ens160') }}"
configure_default_route: "{{ openshift_install_default_route | mandatory }}"
configure_dns_servers: "{{ openshift_install_dns_servers | mandatory }}"

# Openshift spec
configure_network_type: "{{ openshift_install_network_type | default('OpenShiftSDN') }}"
configure_network: "{{ openshift_install_network | mandatory }}"
configure_base_domain: "{{ openshift_install_base_domain | mandatory }}"
configure_cluster_name: "{{ openshift_install_cluster_name | mandatory }}"
configure_ssh_key: "{{ openshift_install_ssh_key | mandatory }}"
configure_pull_secret: "{{ openshift_install_pull_secret | mandatory }}"

configure_binaries_dir: "{{ setup_binaries_dir | d(openshift_install_binaries_dir) | d('/usr/bin') }}"

# DHCP
configure_dhcp: "{{ openshift_install_dhcp | default('false') | bool }}"
configure_dhcp_reservation: "{{ openshift_install_dhcp_reservation | default('true') | bool }}"
configure_dns_provider: "{{ openshift_install_dns | d(lookup('community.hashi_vault.hashi_vault', 'secret={{ openshift_install_vault_secret_dns }} token={{ openshift_install_vault_token }} validate_certs=false url={{ openshift_install_vault_url }}')) }}"