setup_clients_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp"
setup_cluster_name: "{{ openshift_install_cluster_name | mandatory }}"
__setup_binaries_dir: "{{ ansible_env.HOME }}/.{{ setup_cluster_name }}"
setup_binaries_dir: "{{ openshift_install_binary_dir | default(__setup_binaries_dir) }}"
setup_binaries_clean: false
setup_cluster_version: "{{ openshift_install_cluster_version | default('latest') }}"
setup_install_registry: "{{ openshift_install_registry | d(false) }}"
