- name: Include registry
  ansible.builtin.import_tasks: registry.yml
  when: openshift_install_registry | d(false)
  tags:
    - registry

- name: Include setup
  ansible.builtin.import_tasks: setup.yml

- name: Include DHCP reservation
  ansible.builtin.import_tasks: dhcp_reserve.yml

- name: Include install
  ansible.builtin.import_tasks: install.yml
  tags:
    - poweron
