- name: Include registry
  ansible.builtin.import_tasks: registry.yml
  when: configure_registry_cert is not defined or configure_registry_cert == ''
  tags:
    - registry

- name: Include setup
  ansible.builtin.import_tasks: setup.yml

- name: Include DHCP reservation
  ansible.builtin.import_tasks: dhcp_reserve.yml

- name: Include install
  ansible.builtin.import_tasks: install.yml
  tags:
    - poweron
