# Workaround for https://issues.redhat.com/browse/AGENT-626
- name: Workaround | Create cluster manifests
  ansible.builtin.command: "{{ configure_install_binary }} agent create cluster-manifests --dir={{ configure_cluster_home_dir }}"

- name: Workaround | Set userManagedNetworking
  ansible.builtin.lineinfile:
    path: "{{ configure_cluster_home_dir }}/cluster-manifests/agent-cluster-install.yaml"
    firstmatch: true
    insertafter: "networking:$"
    line: "    userManagedNetworking: true"

- name: Workaround | Remove API VIP
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ configure_cluster_home_dir }}/cluster-manifests/agent-cluster-install.yaml"
    regexp: "apiVIP:"

- name: Workaround | Remove ingress VIP
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ configure_cluster_home_dir }}/cluster-manifests/agent-cluster-install.yaml"
    regexp: "ingressVIP:"
