# Workaround for https://issues.redhat.com/browse/AGENT-626
- name: Create cluster manifests
  ansible.builtin.command: "{{ configure_install_binary }} agent create cluster-manifests --dir={{ configure_cluster_home_dir }}"
  environment: "{{ configure_release_env }}"
# Environment must be moved to create image command when this will be removed

- name: Set userManagedNetworking
  ansible.builtin.lineinfile:
    path: "{{ configure_cluster_home_dir }}/cluster-manifests/agent-cluster-install.yaml"
    firstmatch: true
    insertafter: "networking:$"
    line: "    userManagedNetworking: true"

- name: Remove API VIP
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ configure_cluster_home_dir }}/cluster-manifests/agent-cluster-install.yaml"
    regexp: "apiVIP:"

- name: Remove ingress VIP
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ configure_cluster_home_dir }}/cluster-manifests/agent-cluster-install.yaml"
    regexp: "ingressVIP:"
