# Workaround for https://issues.redhat.com/browse/AGENT-626
- name: Create cluster manifests
  ansible.builtin.command: "{{ configure_binaries_dir }}/bin/openshift-install agent create cluster-manifests --dir={{ ansible_env.HOME }}/.{{ openshift_install_cluster_name }}"

- name: Set userManagedNetworking
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.{{ openshift_install_cluster_name }}/cluster-manifests/agent-cluster-install.yaml"
    firstmatch: true
    insertafter: "networking:$"
    line: "    userManagedNetworking: true"

- name: Remove API VIP
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ ansible_env.HOME }}/.{{ openshift_install_cluster_name }}/cluster-manifests/agent-cluster-install.yaml"
    regexp: "apiVIP:"

- name: Remove ingress VIP
  ansible.builtin.lineinfile:
    state: absent
    path: "{{ ansible_env.HOME }}/.{{ openshift_install_cluster_name }}/cluster-manifests/agent-cluster-install.yaml"
    regexp: "ingressVIP:"
