- name: dependencies | Install the necessary linux packages which will be needed later in the ansible run
  ansible.builtin.package:
    name:
      - nmstate
      - podman
      - python3-hvac
      - python3-passlib
      - python3-pip
  become: true

- name: dependencies | Install the necessary pip packages which will be needed later in the ansible run
  ansible.builtin.pip:
    name:
      - infoblox-client
      - aiohttp
