- name: dependencies | Install the necessary linux packages which will be needed later in the ansible run
  ansible.builtin.package:
    name:
      - nmstate
      - python3-aiohttp
      - python3-hvac
      # infloblox-client using pip
  become: true