- name: Set product version
  ansible.builtin.set_fact:
    __product_release_version: "{{ openshift_install_cluster_version | machacekondra.openshift_install.product_release_version }}"
    __family: "{{ 'mac' if ansible_os_family == 'Darwin' else 'linux' }}"

- name: Set the download facts openshift binaries
  ansible.builtin.set_fact:
    __openshift_client: "{{ setup_clients_url }}/{{ __product_release_version }}/openshift-client-{{ __family }}.tar.gz"
    __openshift_install: "{{ setup_clients_url }}/{{ __product_release_version }}/openshift-install-{{ __family }}.tar.gz"

- name: Create ssh keys
  ansible.builtin.include_tasks: ssh.yml
  when: openshift_install_ssh_key is not defined

- name: Include dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Include binaries
  ansible.builtin.include_tasks: binaries.yml
